# @package _global_
model:
  charset_train: " ءآأؤإئابةتثجحخدذرزسشصضطظعغفقكلمنهويًٍَُِّْٖٓٔٗ٠٤٥٫ٰٹپچڈڑژکگںھہۂۃیېےۓ۔۰۱۲۳۴۵۶۷۸۹‘’“”؀؁؂؃؄؅؆؇؈؉؊؋؎؏ؘؙؚؐؑؒؓؕؖؗ؞ػؼؽؾؿٯ٭٪٬!ٴ@؍ؔ؛؟!'\"\\()%*-./0123456789:[]_{}ABCDEFGHIKLMNOPQRSTUWXYZabcdefghijVklmnopJqrstuvwxyz،#$%^,&*+=|><"